# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all tests"
  lane :test do
    scan(
      prelaunch_simulator: true,
      workspace: "rick-and-mort-app.xcworkspace",
      scheme: "Application",
      device: "iPhone 12",
      code_coverage: true,
      open_report: true
    )
  end
end
